CREATE TABLE CLIENTS(
	ID BIGINT PRIMARY KEY,
	NAME VARCHAR(200)
	);

CREATE TABLE PRODUCTS(
	ID_PRODUCT BIGINT AUTO_INCREMENT PRIMARY KEY,
	DESCRIPTION VARCHAR(300),
	PRICE DOUBLE
	);

CREATE TABLE SALES(
	ID_SALE BIGINT AUTO_INCREMENT PRIMARY KEY,
	ID_CLIENT BIGINT,
	DATE DATE
	);

CREATE TABLE SALES_DETAIL(
	ID_SALE_DETAIL BIGINT AUTO_INCREMENT PRIMARY KEY,
	ID_SALE BIGINT,
	ID_PRODUCT BIGINT,
	QUANTITY BIGINT,
	PRICE DOUBLE
	);

CREATE TABLE KARDEX(
	ID_KARDEX BIGINT,
	ID_PRODUCT BIGINT,
	TYPE_TRANSACTION VARCHAR(3),
	ID_TRANSACTION BIGINT,
	QUANTITY BIGINT,
	PRICE DOUBLE
	);